import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { PATHS, fmtNum, zoneFee } from "../lib/data";
import { inputCls, labelCls } from "../components/ui";

type Plan = { id:string; appId:string; name:string; amount:number; recurrence:string; delivery:boolean };
type Zone = { id:string; name:string; feePct:number };
type AppData = { id:string; name:string; appKey:string; color:string; monogram:string; wallets:{moncashName:string;moncashPhone:string;natcashName:string;natcashPhone:string} };

function normalizeHaitianPhone(value:string): string {
 const digits=value.replace(/\D/g,"");
 if(digits.length===8) return `+509${digits}`;
 if(digits.length===11 && digits.startsWith("509")) return `+${digits}`;
 return "";
}

function validHaitianPhone(value:string): boolean {
 return /^\+509\d{8}$/.test(value);
}

export default function PublicHub(){
 const {appId,planId}=useParams<{appId:string;planId:string}>();
 const [app,setApp]=useState<AppData|null>(null),[plans,setPlans]=useState<Plan[]>([]),[zones,setZones]=useState<Zone[]>([]);
 const [selected,setSelected]=useState(planId||""),[name,setName]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[address,setAddress]=useState(""),[zoneId,setZoneId]=useState(""),[method,setMethod]=useState<"moncash"|"natcash">("moncash");
 const [intent,setIntent]=useState<any>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;(async()=>{try{const r=await fetch("/api/apps/"+encodeURIComponent(appId||"")+"/plans",{cache:"no-store"});const b=await r.json();if(!r.ok||!b.success)throw new Error(b.error||"Checkout indisponible.");if(live){setApp(b.app);setPlans(b.plans||[]);setZones(b.zones||[]);setSelected((id)=>b.plans.some((p:Plan)=>p.id===id)?id:(b.plans[0]?.id||""));}}catch(e){if(live)setError(e instanceof Error?e.message:"Erreur de chargement.");}finally{if(live)setLoading(false);}})();return()=>{live=false}},[appId]);
 const plan=useMemo(()=>plans.find(p=>p.id===selected)||null,[plans,selected]);
 const zone=zones.find(z=>z.id===zoneId)||null; const fee=plan&&plan.delivery&&zone?zoneFee(plan.amount,zone.feePct):0; const total=(plan?.amount||0)+fee;
 const wallet=app?.wallets?.[method==="moncash"?"moncashPhone":"natcashPhone"]||""; const walletName=app?.wallets?.[method==="moncash"?"moncashName":"natcashName"]||"";
 const prepare=async()=>{setError("");if(!app||!plan)return;if(name.trim().length<2)return setError("Nom du compte requis.");if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))return setError("Email invalide.");const canonicalPhone=normalizeHaitianPhone(phone);if(!validHaitianPhone(canonicalPhone))return setError("Numéro haïtien invalide. Entrez 8 chiffres (ex. 44617600) ou +509 44617600.");if(plan.delivery&&address.trim().length<6)return setError("Adresse de livraison requise.");if(plan.delivery&&zones.length&&!zone)return setError("Zone de livraison requise.");setLoading(true);try{const r=await fetch("/api/apps/"+encodeURIComponent(app.appKey)+"/payment-intent",{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({planId:plan.id,customerName:name.trim(),email:email.trim(),phone:canonicalPhone,address:plan.delivery?address.trim():null,zoneId:plan.delivery?zoneId:null})});const b=await r.json();if(!r.ok||!b.success)throw new Error(b.error||"Impossible de préparer le paiement.");setIntent(b.intent);}catch(e){setError(e instanceof Error?e.message:"Impossible de préparer le paiement.");}finally{setLoading(false);}};
 if(loading&&!app)return <div className="mx-auto max-w-lg rounded-xl border border-edge bg-panel p-8 text-center text-sm text-fog">Chargement…</div>;
 if(!app||!plan)return <div className="mx-auto max-w-lg rounded-xl border border-edge bg-panel p-8 text-center"><p className="text-snow">{error||"Plan ou application introuvable."}</p><Link className="mt-4 inline-flex rounded-lg bg-gold px-4 py-2 text-sm font-bold text-ink" to={PATHS.apps}>Retour</Link></div>;
 return <div className="mx-auto max-w-lg"><div className="mb-4"><p className="font-display text-sm font-bold text-snow">Hub de Paiement ZakaPro</p><p className="text-[10.5px] text-fog2">Checkout public · plan validé côté serveur</p></div><div className="rounded-xl border border-edge bg-panel p-5 shadow-card">
 <div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl font-bold text-ink" style={{background:app.color}}>{app.monogram}</span><div><p className="text-[11px] font-extrabold uppercase text-fog2">{app.name}</p><p className="font-display text-lg font-bold text-snow">{plan.name}</p></div></div>
 <div className="mt-4"><label className={labelCls}>Plan</label><select className={inputCls} value={selected} onChange={e=>{setSelected(e.target.value);setIntent(null)}}>{plans.map(p=><option key={p.id} value={p.id}>{p.name} — {fmtNum(p.amount)} HTG</option>)}</select></div>
 <div className="mt-3 rounded-lg border border-edge bg-panel2 p-3 text-sm"><div className="flex justify-between text-fog"><span>Prix</span><span>{fmtNum(plan.amount)} HTG</span></div>{plan.delivery&&<div className="mt-1 flex justify-between text-fog"><span>Livraison {zone?"— "+zone.name:""}</span><span>{zone?"+"+fmtNum(fee)+" HTG":"—"}</span></div>}<div className="mt-2 flex justify-between border-t border-edge pt-2 font-bold text-snow"><span>Total</span><span className="text-gold">{fmtNum(total)} HTG</span></div></div>
 {!intent?<div className="mt-4 space-y-3"><div><label className={labelCls}>Nom du compte MonCash/Natcash</label><input className={inputCls} value={name} onChange={e=>setName(e.target.value)}/></div><div><label className={labelCls}>Email</label><input className={inputCls} type="email" value={email} onChange={e=>setEmail(e.target.value)}/></div><div><label className={labelCls}>Téléphone (+509)</label><input className={inputCls} inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="44617600 ou +509 44617600" autoComplete="tel"/></div>{plan.delivery&&<><div><label className={labelCls}>Adresse</label><textarea className={inputCls+" resize-none"} rows={2} value={address} onChange={e=>setAddress(e.target.value)}/></div>{zones.length>0&&<div><label className={labelCls}>Zone</label><select className={inputCls} value={zoneId} onChange={e=>setZoneId(e.target.value)}><option value="">Choisir…</option>{zones.map(z=><option key={z.id} value={z.id}>{z.name} — +{z.feePct}%</option>)}</select></div>}</>}{error&&<p className="text-xs font-bold text-pink-400">{error}</p>}<button disabled={loading} onClick={prepare} className="w-full rounded-xl bg-gold py-3.5 text-sm font-bold text-ink">{loading?"Préparation…":"Continuer vers le paiement"}</button></div>
 :<div className="mt-4 space-y-3"><div className="rounded-lg border border-gold/30 bg-gold/5 p-4"><p className="text-[10px] font-extrabold uppercase text-gold">Instructions</p><p className="mt-2 text-sm text-snow">Envoyez exactement <b>{fmtNum(Number(intent.total_amount))} HTG</b> à <b>{wallet||"numéro marchand non configuré"}</b>{walletName&&" au nom de "+walletName}.</p><p className="mt-2 text-xs text-fog">Référence obligatoire : <code className="text-gold">{intent.reference}</code></p><p className="mt-2 text-xs text-fog2">Le listener exige la même référence, le même nom, le même numéro et le montant exact.</p></div><div className="grid grid-cols-2 gap-2"><button onClick={()=>setMethod("moncash")} className={`rounded-lg py-3 text-xs font-bold text-white ${method==="moncash"?"bg-blue-600":"bg-blue-600/50"}`}>MonCash</button><button onClick={()=>setMethod("natcash")} className={`rounded-lg py-3 text-xs font-bold text-white ${method==="natcash"?"bg-violet-600":"bg-violet-600/50"}`}>Natcash</button></div><p className="text-center text-xs text-fog2">La confirmation réelle vient du SMS Listener. Cette page ne simule plus un paiement réussi.</p><button onClick={()=>setIntent(null)} className="w-full rounded-lg border border-edge py-2 text-xs font-bold text-fog">Modifier</button></div>}
 </div><p className="mt-3 text-center text-[10px] text-fog2">Application isolée · app_key → planId → intention → SMS exact</p></div>;
}